"""add xyz

Revision ID: 1f0bf593a424
Revises: 7a4818ef2dc7
Create Date: 2026-02-09 18:35:08.405950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f0bf593a424'
down_revision: Union[str, Sequence[str], None] = '7a4818ef2dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # drop join/association tables first (they depend on parents)
    op.drop_table('cheat_topics')
    op.drop_table('cheat_platforms')
    op.drop_table('user_cheats')

    # drop parent tables after dependents are gone
    op.drop_index(op.f('ix_cheats_created_by_user_id'), table_name='cheats')
    op.drop_index(op.f('ix_cheats_id'), table_name='cheats')
    op.drop_index(op.f('ix_cheats_title'), table_name='cheats')
    op.drop_table('cheats')

    op.drop_index(op.f('ix_topics_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_name'), table_name='topics')
    op.drop_index(op.f('ix_topics_slug'), table_name='topics')
    op.drop_table('topics')

    op.drop_index(op.f('ix_platforms_id'), table_name='platforms')
    op.drop_index(op.f('ix_platforms_name'), table_name='platforms')
    op.drop_index(op.f('ix_platforms_slug'), table_name='platforms')
    op.drop_table('platforms')

    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('platforms',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=80), nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platforms_slug'), 'platforms', ['slug'], unique=True)
    op.create_index(op.f('ix_platforms_name'), 'platforms', ['name'], unique=True)
    op.create_index(op.f('ix_platforms_id'), 'platforms', ['id'], unique=False)
    op.create_table('cheat_platforms',
    sa.Column('cheat_id', sa.INTEGER(), nullable=False),
    sa.Column('platform_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['cheat_id'], ['cheats.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.PrimaryKeyConstraint('cheat_id', 'platform_id')
    )
    op.create_table('user_cheats',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('cheat_id', sa.INTEGER(), nullable=False),
    sa.Column('is_favorite', sa.BOOLEAN(), nullable=False),
    sa.Column('personal_notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['cheat_id'], ['cheats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'cheat_id')
    )
    op.create_table('cheat_topics',
    sa.Column('cheat_id', sa.INTEGER(), nullable=False),
    sa.Column('topic_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['cheat_id'], ['cheats.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('cheat_id', 'topic_id')
    )
    op.create_table('cheats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('code', sa.TEXT(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_by_user_id', sa.INTEGER(), nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('metadata_tag', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cheats_title'), 'cheats', ['title'], unique=False)
    op.create_index(op.f('ix_cheats_id'), 'cheats', ['id'], unique=False)
    op.create_index(op.f('ix_cheats_created_by_user_id'), 'cheats', ['created_by_user_id'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_slug'), 'topics', ['slug'], unique=True)
    op.create_index(op.f('ix_topics_name'), 'topics', ['name'], unique=True)
    op.create_index(op.f('ix_topics_id'), 'topics', ['id'], unique=False)
    # ### end Alembic commands ###
